name: Feature Request
description: Suggest an idea for Code-Guardian
title: "[Feature]: "
labels: ["enhancement", "feature-request"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature for Code-Guardian!
        
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
      
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component of Code-Guardian does this feature relate to?
      options:
        - CLI Interface
        - Core Scanning Engine
        - Output Formatters
        - Storage/Database
        - Configuration
        - Documentation
        - CI/CD
        - Other (specify in description)
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Critical for adoption
        - Urgent - Blocking current work
    validations:
      required: true
      
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature
      placeholder: |
        How would you use this feature?
        What workflow would it enable?
        What value would it provide?
    validations:
      required: true
      
  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of how this feature might work
      placeholder: |
        Command line examples:
        ```bash
        code-guardian scan --new-feature
        ```
        
        Configuration examples:
        ```toml
        [new_feature]
        enabled = true
        ```
    validations:
      required: false
      
  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Willingness
      description: Are you willing to contribute to implementing this feature?
      options:
        - label: I'd like to implement this feature myself
        - label: I can help with testing
        - label: I can help with documentation
        - label: I'm available for consultation/feedback
        
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true