name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable]
    steps:
    - uses: actions/checkout@v4
      with:
        path: code-guardian
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          code-guardian/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('code-guardian/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    - name: Check
      run: cargo check --workspace
      working-directory: code-guardian
    - name: Test
      run: cargo test --workspace
      working-directory: code-guardian
    - name: Clippy
      run: cargo clippy --workspace -- -D warnings
      working-directory: code-guardian
    - name: Format
      run: cargo fmt --all -- --check
      working-directory: code-guardian
    - name: Build release
      run: cargo build --release --workspace
      working-directory: code-guardian
    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: binaries-${{ matrix.os }}
        path: code-guardian/target/release/