name: Security Scan

on:
  workflow_call:
    inputs:
      audit:
        description: 'Run cargo audit'
        type: boolean
        default: true
      deny:
        description: 'Run cargo deny checks'
        type: boolean
        default: true
      gitleaks:
        description: 'Run gitleaks secrets detection'
        type: boolean
        default: true
      clippy-security:
        description: 'Run security-focused clippy checks'
        type: boolean
        default: true

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - uses: ./.github/actions/setup-rust

      - uses: ./.github/actions/setup-cache

      - uses: ./.github/actions/run-security-scan
        with:
          audit: ${{ inputs.audit }}
          deny: ${{ inputs.deny }}
          gitleaks: ${{ inputs.gitleaks }}
          clippy-security: ${{ inputs.clippy-security }}