name: Test

on:
  workflow_call:
    inputs:
      package:
        description: 'Specific package to test (leave empty for workspace)'
        type: string
        default: ''
      os:
        description: 'Operating system matrix'
        type: string
        default: '["ubuntu-latest", "windows-latest", "macos-latest"]'
      rust-version:
        description: 'Rust version matrix'
        type: string
        default: '["stable"]'

      nextest:
        description: 'Use cargo-nextest'
        type: boolean
        default: true
      coverage:
        description: 'Generate coverage reports'
        type: boolean
        default: false
      coverage-threshold:
        description: 'Coverage threshold percentage'
        type: number
        default: 82

jobs:
  test:
    name: Test (${{ matrix.os }}, ${{ matrix.rust }})
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      actions: write
    strategy:
      matrix:
        os: ${{ fromJSON(inputs.os) }}
        rust: ${{ fromJSON(inputs.rust-version) }}
        include:
          - os: ubuntu-latest
            rust: beta
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493

      - uses: ./.github/actions/setup-rust
        with:
          toolchain: ${{ matrix.rust }}

      - uses: ./.github/actions/setup-cache
        with:
          cache-key-suffix: ${{ matrix.os }}-${{ matrix.rust }}

      - uses: ./.github/actions/build-workspace

      - uses: ./.github/actions/run-tests
        with:
          package: ${{ inputs.package }}
          nextest: ${{ inputs.nextest }}
          install-nextest: true

      - name: Run doc tests
        run: cargo test --doc --workspace

       - uses: ./.github/actions/generate-coverage
         if: ${{ inputs.coverage && matrix.os == 'ubuntu-latest' && matrix.rust == 'stable' }}
         with:
           threshold: ${{ inputs.coverage-threshold }}
           install-llvm-cov: true

       - name: Upload coverage reports
         if: ${{ inputs.coverage && matrix.os == 'ubuntu-latest' && matrix.rust == 'stable' }}
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        with:
          name: coverage-reports
          path: |
            lcov.info
            coverage/