[book]
title = "Code Guardian Documentation"
description = "Comprehensive documentation for Code Guardian security scanner"
authors = ["Code Guardian Team"]
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "book"
create-missing = true

[preprocessor.links]
# Enable link checking

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
smart-punctuation = true
mathjax-support = false
copy-fonts = true
# additional-css = ["custom.css"]
# additional-js = ["custom.js"]
git-repository-url = "https://github.com/your-org/code-guardian"
edit-url-template = "https://github.com/your-org/code-guardian/edit/main/docs/{path}"

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[output.html.print]
enable = true

[output.html.fold]
enable = false
level = 0