name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '30 1 * * *'  # Run daily at 1:30 AM UTC
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        
        # Issue configuration
        stale-issue-message: |
          This issue has been automatically marked as stale because it has not had recent activity. 
          It will be closed if no further activity occurs within 7 days.
          
          If this issue is still relevant, please:
          - Comment on this issue to keep it open
          - Provide additional information if requested
          - Consider submitting a pull request if you can help resolve it
          
          Thank you for your contributions to Code-Guardian! 🛡️
        
        close-issue-message: |
          This issue has been automatically closed due to inactivity.
          
          If you believe this issue is still relevant, please feel free to reopen it or create a new issue 
          with updated information.
        
        # Pull request configuration  
        stale-pr-message: |
          This pull request has been automatically marked as stale because it has not had recent activity.
          It will be closed if no further activity occurs within 7 days.
          
          If this pull request is still relevant, please:
          - Rebase your branch against the latest main/develop
          - Address any review comments
          - Comment on this PR to keep it open
          
          Thank you for your contribution to Code-Guardian! 🚀
        
        close-pr-message: |
          This pull request has been automatically closed due to inactivity.
          
          If you'd like to continue working on this change, please feel free to reopen this PR or 
          create a new one with updated code.
        
        # Timing configuration
        days-before-stale: 30
        days-before-close: 7
        days-before-pr-close: 7
        
        # Label configuration
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        exempt-issue-labels: 'pinned,security,enhancement,good first issue'
        exempt-pr-labels: 'pinned,security,work-in-progress'
        
        # Additional configuration
        operations-per-run: 100
        remove-stale-when-updated: true
        ascending: true
        
        # Don't mark as stale if these labels are present
        exempt-all-issue-assignees: true
        exempt-all-pr-assignees: true